In [3]:
import numpy as np
from datetime import date, timedelta

# Create a 3x3x3 array with random values

In [4]:
arr = np.random.rand(3,3,3)
arr

array([[[0.88658929, 0.1557995 , 0.13219405],
        [0.55550395, 0.08854225, 0.23288461],
        [0.61435943, 0.79489481, 0.38555243]],

       [[0.06828092, 0.51959128, 0.52464186],
        [0.85928431, 0.78889819, 0.65328487],
        [0.34648718, 0.30018814, 0.31939057]],

       [[0.3347083 , 0.59490703, 0.07219084],
        [0.91300171, 0.33994951, 0.5599222 ],
        [0.12517988, 0.34074636, 0.94523405]]])

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Normalize a 5x5 random matrix

In [8]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.97637514,  0.11532276, -1.07022139, -0.07532994, -0.14785956],
       [ 1.94575161, -0.30113185,  0.10199389, -0.3523184 ,  0.51899096],
       [ 0.44863026, -1.14168176,  0.61911252, -0.19233937, -0.78700347],
       [-1.6462264 , -0.28939779,  1.38413153,  1.68595644,  1.64575626],
       [ 0.65775098,  1.1879868 , -0.76253243, -1.44227896, -1.12668754]])

# How to find common values between two arrays

In [9]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([0, 1, 5, 6])

# How to get the dates of yesterday, today and tomorrow?

In [16]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday:",yesterday,",","Today:", today,",","Tommorrow:", tomorrow)

Yesterday: 2020-07-30 , Today: 2020-07-31 , Tommorrow: 2020-08-01


# Consider two random array A and B, check if they are equal

In [17]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.76309029 0.6372603  0.1992425 ]
 [0.73839059 0.23268927 0.41263039]
 [0.34829166 0.80724405 0.64961105]]


Array2:
[[0.15736581 0.06505848 0.66218052]
 [0.00226884 0.30941059 0.90629162]
 [0.62448482 0.74634257 0.42377678]]


Equality: False


# Create random vector of size 10 and replace the maximum value by 0

In [18]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.77211   , 0.6371088 , 0.09016124, 0.28416163, 0.57932659,
       0.12631635, 0.        , 0.83816684, 0.35406283, 0.38080484])

# How to print all the values of an array?

In [19]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [20]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.10522257, -0.32669263,  0.4319152 ],
       [ 0.3742483 , -0.29407899, -0.08016932],
       [-0.04526185,  0.10128943, -0.05602758]])

# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [26]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([3., 2., 5., 3., 2.])

# How to get the diagonal of a dot product?

In [27]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([81, 40, 72])

# How to find the most frequent value in an array?

In [28]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[4 5 1 7 7 3 9 4 6 7 9 8 5 6 7 7 3 1 0 3]


7

# How to get the n largest values of an array?

In [29]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

7

# How to create a record array from a regular array?

In [30]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])